name: dotnet test

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
<<<<<<< HEAD
  test:
=======
  check-tests:
>>>>>>> 31ff24336ba59c5bb27925b89e9ed8cefabb060a
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Run all test
        run: dotnet test